name: contrast
channels:
  - defaults
  - conda-forge
  - simpleitk
dependencies:
  - matplotlib=3.5.2
  - pandas=1.4
  - python=3.9
  - pyyaml=6.0
  - pip
  - scikit-image=0.19
  - simpleitk
  - statsmodels=0.13
  - tensorflow=2.9.1