name: contrast
channels:
  - defaults
  - conda-forge
  - simpleitk
dependencies:
  - pip=20.1.1
  - python>=3.7
  - matplotlib>=3.4
  - pandas>=1.3
  - pyyaml=6.0
  - scikit-image>=0.18
  - simpleitk>=2.1
  - statsmodels=0.13
  - tensorflow=2.9.1