name: contrast
channels:
  - defaults
  - conda-forge
  - simpleitk
dependencies:
  - pip=20.1.1
  - python=3.9
  - cudatoolkit=11.2
  - cudnn=8.1.0
  - matplotlib=3.5.2
  - pandas=1.4
  - pyyaml=6.0
  - scikit-image=0.19
  - simpleitk
  - statsmodels=0.13
  - pip:
    - tensorflow==2.9.1